### ISSUE TITLE
Hawker Cadastro Vendedoras 

### ISSUE THREAD

**Issue by suporte4katianne** [hsisistemas/sistema-basico#1]
Não está salvando a informação cadastrada no campo Observação no cadastro da vendedora

**Comment by suporte4katianne** [comment]
Permitir cadastrar vendedora sem cpf, adicionar campo data de nascimento

**Comment by erielmiquilino** [comment]
Olá, Versão 1.1.2:

- Correção no bug 

> Não está salvando a informação cadastrada no campo Observação no cadastro da vendedor

campo observação esta guardando informações

- Adicionado campo data de nascimento, em preferencias > configurações adcionado possibilidade de escolha para validação de CPFs e CNPJs conforme

> Permitir cadastrar vendedora sem cpf, adicionar campo data de nascimento
