### ISSUE TITLE
Abertura de caixa para inicio de atendimento

### ISSUE THREAD

**Issue by HortencioFlavio** [hsisistemas/sistema-basico#11]
Processo para abertura de caixa diario para inicio dos atendimentos. A tela de lancamento de caixa somente devera ser apresentada ao usuario apos a abertura de caixa realizada. Informar valor de inicio de dia (Troco).

**Comment by erielmiquilino** [comment]
isso ficaria presente no menu Atendimento como abertura de caixa?

a forma correta para produção deste tópico não seria um PDV?
