### ISSUE TITLE
Hawker Edição de Remessa

### ISSUE THREAD

**Issue by suporte4katianne** [hsisistemas/sistema-basico#2]
Permitir a edição de uma remessa salvando aos poucos

**Comment by erielmiquilino** [comment]
Olá! Versão 1.1.2

Implementada possibilidade de alteração de uma remessa já editada, sendo assim se torna possível a manipulação dos dados dos kits inclusos na remessa de forma parcial conforme necessidade 

> Permitir a edição de uma remessa salvando aos poucos
