### ISSUE TITLE
Correção envio de email pelo sistema hsi basico

### ISSUE THREAD

**Issue by HortencioFlavio** [hsisistemas/sistema-basico#3]
Conformes teste unitario no modulo de emissao de nf-e, apos a nota fiscal autorizada, o envio automatico do email nao foi realizado. Foram alternadas diferentes contas de email configuradas para envio e nenhuma das contas de email configuradas obteve exito no envio.

email´s testados flandavo@hotmail.com, flavio_pereira@uniplaclages.edu.br e flavio@hsiautomacao.com.br

no cadastro da empresa esta fixo o email flandavo@hotmail.com

**Comment by erielmiquilino** [comment]
fixado na versão v1.1.6

segundo necessidade informada, sistema agora envia emails a partir de documentos eletrônicos
